//PROBLEM SOLVING

/*

& UNDERSTAND THE PROBLEM
& EXPLORE CONCRETE EXAMPLES
& BREAK IT DOWN 
& SOLVE / SIMPLIFY
& LOOK BACK AND REFACTOR

*/

//*  UNDERSTANDING THE PROBLEM

// 1. Can I restate the problem in my own words?
// 2. What are the inputs that go into the problem?
// 3. What are the outputs?
// 4. Can the outputs be determined from the inputs?
// 5. What are the things that really matter in this problem?

//^ WRITE A FUNCTION WHICH TAKES TWO NUMBERS AND RETURNS THEIR SUM.
// 1. Can I restate the problem in my own words?
// ^ We create a function which takes two numbers, calculates the sum and returns the result of that sum
// 2. What are the inputs that go into the problem?
//^ The inputs are two numbers, they can be integers, negative or positive numbers, floats etc. What if someone forgets to put in the second input, or what if someone inputs more arguments in the function call?
// 3. What are the outputs?
//^ This depends mostly on the inputs
// 4. Can the outputs be determined from the inputs?
//^ usually yes.
// 5. What are the things that really matter in this problem?
//^
